/**
 * Build-time blog generator.
 * Reads `src/content/blog/posts/*.md` → writes:
 *   - `src/content/blog-posts.generated.ts` (typed post registry for app + prerender)
 *   - `public/blog/rss.xml` (copied into dist by Vite)
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadEnv } from "vite";
import { parseFrontmatter } from "../src/lib/blog/parse-frontmatter";
import {
  estimateReadingTimeMinutes,
  extractFaqsFromMarkdown,
  markdownToHtml,
} from "../src/lib/blog/markdown-to-html";
import type { BlogPost } from "../src/lib/blog/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const postsDir = join(rootDir, "src", "content", "blog", "posts");
const generatedPath = join(rootDir, "src", "content", "blog-posts.generated.ts");
const publicRssPath = join(rootDir, "public", "blog", "rss.xml");
const distRssPath = join(rootDir, "dist", "blog", "rss.xml");

function resolveOrigin(): string {
  const mode = process.env.MODE || "production";
  Object.assign(process.env, loadEnv(mode, rootDir, ""), loadEnv(mode, join(rootDir, ".."), ""));
  const raw =
    (typeof process.env.VITE_SITE_URL === "string" && process.env.VITE_SITE_URL.trim()) ||
    "https://www.mercyspeaksdigital.com";
  return raw.replace(/\/$/, "");
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function asString(value: unknown, fallback = ""): string {
  if (typeof value === "string") return value.trim();
  if (typeof value === "number") return String(value);
  return fallback;
}

function asStringArray(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map((v) => String(v).trim()).filter(Boolean);
  }
  if (typeof value === "string" && value.trim()) {
    return [value.trim()];
  }
  return [];
}

function asBool(value: unknown, fallback = false): boolean {
  if (typeof value === "boolean") return value;
  if (value === "true") return true;
  if (value === "false") return false;
  return fallback;
}

function toIsoDate(raw: string): string {
  if (!raw) return new Date().toISOString().slice(0, 10);
  // Accept YYYY-MM-DD or full ISO; normalize date-only for consistency
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) return raw;
  return d.toISOString();
}

function loadPostsFromDisk(): BlogPost[] {
  if (!existsSync(postsDir)) {
    mkdirSync(postsDir, { recursive: true });
    return [];
  }

  const files = readdirSync(postsDir)
    .filter((name) => name.endsWith(".md") && !name.startsWith("_"))
    .sort();

  const posts: BlogPost[] = [];

  for (const file of files) {
    const slug = file.replace(/\.md$/i, "");
    const raw = readFileSync(join(postsDir, file), "utf8");
    const { data, content } = parseFrontmatter(raw);
    const title = asString(data.title);
    const description = asString(data.description);
    if (!title || !description) {
      console.warn(`[generate-blog] Skipping ${file}: title and description are required.`);
      continue;
    }

    const publishedAt = toIsoDate(asString(data.publishedAt));
    const updatedRaw = asString(data.updatedAt);
    const updatedAt = updatedRaw ? toIsoDate(updatedRaw) : undefined;
    const { html, headings } = markdownToHtml(content);
    const readingTimeMinutes = estimateReadingTimeMinutes(content);
    const faqs = extractFaqsFromMarkdown(content);
    const ogImage = asString(data.ogImage || data.ogImagePath);
    const metaTitle = asString(data.metaTitle);
    const excerpt =
      description ||
      content
        .replace(/^#+\s+.+$/gm, "")
        .replace(/\s+/g, " ")
        .trim()
        .slice(0, 200);

    posts.push({
      slug,
      path: `/blog/${slug}`,
      title,
      description,
      metaTitle: metaTitle || undefined,
      publishedAt,
      updatedAt,
      tags: asStringArray(data.tags),
      draft: asBool(data.draft, false),
      readingTimeMinutes,
      ogImagePath: ogImage || undefined,
      ctaTitle: asString(data.ctaTitle) || undefined,
      ctaDescription: asString(data.ctaDescription) || undefined,
      useLiveDemoCta: asBool(data.useLiveDemoCta, true),
      html,
      headings,
      excerpt,
      faqs,
    });
  }

  // Newest first
  posts.sort((a, b) => {
    const ta = new Date(a.publishedAt).getTime();
    const tb = new Date(b.publishedAt).getTime();
    return tb - ta;
  });

  return posts;
}

function serializeTs(posts: BlogPost[]): string {
  const json = JSON.stringify(posts, null, 2);
  return `/**
 * AUTO-GENERATED by scripts/generate-blog.ts — do not edit by hand.
 * Source: src/content/blog/posts/*.md
 */
import type { BlogPost } from "@/lib/blog/types";

export const GENERATED_BLOG_POSTS: BlogPost[] = ${json};
`;
}

function buildRssXml(origin: string, posts: BlogPost[]): string {
  const published = posts.filter((p) => !p.draft);
  const channelLink = `${origin}/blog`;
  const items = published
    .map((post) => {
      const link = `${origin}${post.path}`;
      const pubDate = new Date(post.publishedAt).toUTCString();
      return `  <item>
    <title>${escapeXml(post.title)}</title>
    <link>${escapeXml(link)}</link>
    <guid isPermaLink="true">${escapeXml(link)}</guid>
    <pubDate>${escapeXml(pubDate)}</pubDate>
    <description>${escapeXml(post.description)}</description>
  </item>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Mercy Speaks Digital Blog</title>
    <link>${escapeXml(channelLink)}</link>
    <description>AI receptionists, websites, and automation insights for small businesses.</description>
    <language>en-us</language>
    <atom:link href="${escapeXml(`${origin}/blog/rss.xml`)}" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;
}

function writeFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
}

function main(): void {
  const origin = resolveOrigin();
  const posts = loadPostsFromDisk();
  const publishedCount = posts.filter((p) => !p.draft).length;

  writeFile(generatedPath, serializeTs(posts));
  const rss = buildRssXml(origin, posts);
  writeFile(publicRssPath, rss);
  if (existsSync(join(rootDir, "dist"))) {
    writeFile(distRssPath, rss);
  }

  console.log(
    `blog: ${posts.length} post(s) (${publishedCount} published) → blog-posts.generated.ts + blog/rss.xml`
  );
}

main();
